// Nakima v1 clinic data layer.
// Static seed data — will be replaced by Lovable Cloud (Supabase) in a later
// iteration. Structure is designed so the DB migration is a straight mapping:
// one row per clinic, one row per (clinic, service) join, cities as a table.
//
// v1 scope: naprapat only, top 5 cities. Only Stockholm is populated with
// clinics; other cities render an "kommer snart" state.

export type ServiceSlug = "naprapat" | "kiropraktor" | "massage";

export type CitySlug =
  | "stockholm"
  | "goteborg"
  | "malmo"
  | "uppsala"
  | "vasteras";

export interface City {
  slug: CitySlug;
  name: string;
  region: string;
  // Short editorial intro used in city hero + meta description.
  intro: string;
}

export interface Clinic {
  slug: string;
  name: string;
  city: CitySlug;
  neighborhood: string;
  street: string;
  postal: string;
  services: ServiceSlug[];
  // Redaktionell one-liner about the clinic's profile.
  blurb: string;
  // 0–5, one decimal. Editorial score, not user reviews (those come in v2).
  rating: number;
  reviewCount: number;
  // Price range indicator: 1–3 ("kr", "kr kr", "kr kr kr").
  priceLevel: 1 | 2 | 3;
  // Public booking URL (affiliate slot). Null = "kontakta kliniken".
  bookingUrl: string | null;
  phone: string;
  // WGS84 coordinates (approx, from neighborhood centroid until per-clinic geocoding).
  lat?: number;
  lng?: number;
  featured?: boolean;
  // ISO date (YYYY-MM-DD) — when this clinic's record was last verified/edited.
  // Feeds sitemap <lastmod> per URL. Defaults to DATASET_UPDATED_AT if omitted.
  updatedAt?: string;
  // Optional enrichment fields (populated per clinic when available; page
  // falls back to editorial defaults when missing). Structured for LLM
  // extraction + rich MedicalBusiness schema.
  openingHours?: Partial<Record<
    "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun",
    string // "08:00–18:00" or "Stängt"
  >>;
  established?: number; // grundläggningsår
  languages?: string[]; // ["Svenska", "Engelska"]
  specialties?: string[]; // ["Idrottsskador", "Nack- och ryggsmärta"]
  paymentMethods?: string[]; // ["Swish", "Kort", "Faktura"]
  accessibility?: string[]; // ["Hiss", "Rullstolsanpassad"]
  website?: string;
}




// Global fallback used for URLs that don't carry their own updatedAt
// (homepage, city index) and as the default for clinic rows without one.
// Bump this whenever the seed dataset is regenerated.
export const DATASET_UPDATED_AT = "2026-07-02";

export const cities: City[] = [
  {
    slug: "stockholm",
    name: "Stockholm",
    region: "Stockholms län",
    intro:
      "Stockholm har Sveriges tätaste utbud av manuell medicin. Här hittar du legitimerade naprapater från Vasastan till Hammarby Sjöstad – redaktionellt granskade och sorterade efter specialistområde.",
  },
  {
    slug: "goteborg",
    name: "Göteborg",
    region: "Västra Götaland",
    intro:
      "Göteborgs naprapatklinker samlade på ett ställe. Vi utökar löpande – hör av dig om din klinik saknas.",
  },
  {
    slug: "malmo",
    name: "Malmö",
    region: "Skåne",
    intro:
      "Naprapater i Malmö och Öresundsregionen. Vi utökar löpande under 2026.",
  },
  {
    slug: "uppsala",
    name: "Uppsala",
    region: "Uppsala län",
    intro: "Naprapater i Uppsala. Katalogen växer varje vecka.",
  },
  {
    slug: "vasteras",
    name: "Västerås",
    region: "Västmanland",
    intro: "Naprapater i Västerås. Katalogen växer varje vecka.",
  },
];

export const serviceLabels: Record<ServiceSlug, { singular: string; plural: string }> = {
  naprapat: { singular: "Naprapat", plural: "Naprapater" },
  kiropraktor: { singular: "Kiropraktor", plural: "Kiropraktorer" },
  massage: { singular: "Massör", plural: "Massörer" },
};

// Stockholm seed — imported from Hyperagent scrape (2026-07-01), 56 verified
// naprapater. Structure maps 1:1 to the future Cloud (Supabase) schema.
export const clinics: Clinic[] = [
  {
    slug: "naprapat-rehab",
    name: "Naprapat-Rehab",
    city: "stockholm",
    neighborhood: "Bromma",
    street: "Registervägen 28",
    postal: "168 31 Bromma",
    services: ["naprapat"],
    blurb: "Bromma Naprapat & Rehab AB har bedrivit naprapatverksamhet sedan 2013 med specialisering på droppteknik. Kliniken erbjuder naprapatbehandling och massage med tydligt fokus på att förklara smärtorsaker och ge patienten verktyg för självhjälp.",
    rating: 5.0,
    reviewCount: 127,
    priceLevel: 2,
    bookingUrl: "https://www.naprapat-rehab.se/boka-tid/",
    phone: "08-646 21 40",
    lat: 59.34142,
    lng: 17.93963,
    openingHours: {"mon": "07:30–19:30", "tue": "07:30–19:30", "wed": "07:30–19:30", "thu": "07:30–19:30", "fri": "07:30–16:30", "sat": "Stängt", "sun": "Stängt"},
  },
  {
    slug: "naprapatimperiet-bromma-ab",
    name: "Naprapatimperiet Bromma AB",
    city: "stockholm",
    neighborhood: "Bromma",
    street: "Tummelisas gata 9",
    postal: "168 72 Bromma",
    services: ["naprapat"],
    blurb: "Naprapatimperiet Bromma är en lokal naprapatklinik i Annedal med inriktning mot naprapati och idrottsskador. Kliniken betonar noggrann undersökning, individanpassad rehabilitering och klinisk erfarenhet från bl.a. Superettan.",
    rating: 5.0,
    reviewCount: 24,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/naprapatimperiet-bromma-43280",
    phone: "070-739 64 54",
    lat: 59.34033,
    lng: 17.94062,
    featured: true,
    openingHours: {"mon": "08:00–19:00", "tue": "09:00–18:30", "wed": "10:00–18:30", "thu": "08:00–18:30", "fri": "08:00–17:00", "sat": "Stängt", "sun": "10:00–16:00"},
    established: 2021,
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Dry needling"],
    paymentMethods: ["Friskvårdsbidrag"],
  },
  {
    slug: "naprapatdoktorerna-i-stockholm-hb",
    name: "Naprapatdoktorerna i Stockholm HB",
    city: "stockholm",
    neighborhood: "Bromma",
    street: "Abrahamsbergsvägen 31",
    postal: "168 31 Bromma",
    services: ["naprapat", "massor"],
    blurb: "Naprapatdoktorerna i Bromma är en av Stockholms etablerade naprapatkliniker med verksamhet sedan 1994, belägen nära Abrahamsbergs tunnelbanestation. Kliniken erbjuder naprapati, akupunktur och massage utfört av legitimerade naprapater.",
    rating: 4.8,
    reviewCount: 32,
    priceLevel: 2,
    bookingUrl: "https://napdokbromma.bestille.no/OnCust2/#!/",
    phone: "08-26 33 88",
    lat: 59.34171,
    lng: 17.94288,
    featured: true,
    openingHours: {"mon": "07:00–18:00", "tue": "07:00–18:00", "wed": "07:00–18:00", "thu": "07:00–18:00", "fri": "07:00–18:00"},
  },
  {
    slug: "agilokliniken-hagastaden-torsplan",
    name: "Agilokliniken Hagastaden (Torsplan)",
    city: "stockholm",
    neighborhood: "Hagastaden",
    street: "Solnavägen 3",
    postal: "G, 113 63 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatklinik i Hagastaden vid Torsplan, Solnavägen 3 G, med specialisering inom stötvågsbehandling och diagnostiskt ultraljud, nära Nya Karolinska.",
    rating: 5.0,
    reviewCount: 44,
    priceLevel: 3,
    bookingUrl: null,
    phone: "08-872007",
    lat: 59.34918,
    lng: 18.03093,
    featured: true,
    openingHours: {"mon": "09:00–18:00", "tue": "08:00–18:30", "wed": "09:00–18:30", "thu": "08:00–17:00", "fri": "07:00–14:30"},
    specialties: ["Stötvågsbehandling", "Nack- och ryggsmärta", "Idrottsskador", "Medicinsk akupunktur"],
  },
  {
    slug: "naprapatspecialisten-hammarby-sjostad",
    name: "Naprapatspecialisten Hammarby Sjöstad",
    city: "stockholm",
    neighborhood: "Hammarby Sjöstad",
    street: "Lugnets Allé 48F",
    postal: "120 66 Stockholm",
    services: ["naprapat"],
    blurb: "Etablerad naprapatklinik i Hammarby Sjöstad på Lugnets Allé 48F, grundad 2013 av Louise Olsson och André Lysell. Kliniken är ansluten till Svenska Naprapatförbundet och erbjuder naprapati, dry needling och laserterapi.",
    rating: 5.0,
    reviewCount: 91,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/naprapatspecialisten-61949",
    phone: "08-410 77 340",
    lat: 59.30477,
    lng: 18.09865,
    featured: true,
    openingHours: {"mon": "06:45–19:00", "tue": "06:45–19:00", "wed": "06:45–19:00", "thu": "06:45–19:00", "fri": "06:45–19:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Ischias", "Huvudvärk", "Graviditetsbesvär", "Dry needling"],
  },
  {
    slug: "pure-motion-naprapat-massage-och-rehab-hammarby-sjostad",
    name: "Pure Motion: Naprapat, Massage & Rehab Hammarby Sjöstad",
    city: "stockholm",
    neighborhood: "Hammarby Sjöstad",
    street: "Hammarby Kaj 52",
    postal: "120 63 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "Naprapatklinik i Hammarby Sjöstad på Hammarby Kaj 52, driven av Maria Franfie och Tobias Sandell Yxner som utbildades vid Naprapathögskolan 2011. Erbjuder naprapati, massage och rehabilitering.",
    rating: 5.0,
    reviewCount: 72,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/pure-motion-sthlm-36919",
    phone: "+46 73-653 04 88",
    lat: 59.30416,
    lng: 18.10103,
    openingHours: {"mon": "07:30–19:00", "tue": "07:30–19:00", "wed": "07:30–19:00", "thu": "07:30–19:00", "fri": "07:30–19:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Dry needling", "Nack- och ryggsmärta"],
  },
  {
    slug: "access-rehab-naprapat-och-sjukgymnast-i-hammarby-sjostad",
    name: "Access Rehab Naprapat & Sjukgymnast i Hammarby Sjöstad",
    city: "stockholm",
    neighborhood: "Hammarby Sjöstad",
    street: "Hammarby allé 150",
    postal: "120 66 Stockholm",
    services: ["naprapat"],
    blurb: "Multidisciplinär klinik i Hammarby Sjöstad på Hammarby Allé 150 med naprapater, sjukgymnaster och kiropraktorer. Inget remissbehov; erbjuder även ultraljudsundersökning och stötvågsbehandling.",
    rating: 4.7,
    reviewCount: 89,
    priceLevel: 2,
    bookingUrl: null,
    phone: "010-202 30 20",
    lat: 59.30358,
    lng: 18.09949,
    featured: true,
    openingHours: {"mon": "07:45–21:00", "tue": "07:45–21:00", "wed": "07:45–21:00", "thu": "07:45–21:00", "fri": "07:45–18:00", "sat": "08:00–14:00", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Graviditetsbesvär"],
    paymentMethods: ["Friskvårdsbidrag", "ePassi", "Benify", "Wellnet"],
    accessibility: ["Parkering", "Nära T-bana"],
  },
  {
    slug: "nordic-kiropraktik-naprapati-och-massage-kista",
    name: "Nordic Kiropraktik Naprapati & Massage - Kista",
    city: "stockholm",
    neighborhood: "Kista",
    street: "Hanstavägen 55",
    postal: "164 53 Kista",
    services: ["naprapat", "massor"],
    blurb: "Nordic Kiropraktik, Naprapati & Massage i Kista Galleria är en klinik med kiropraktik som primär inriktning, men erbjuder även naprapati, massage och dry needling. Behandling kräver ingen remiss.",
    rating: 4.9,
    reviewCount: 174,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/nordic-kiropraktik-naprapati-massage-36686",
    phone: "08-20 22 52",
    lat: 59.40345,
    lng: 17.94422,
    openingHours: {"mon": "08:00–20:00", "tue": "08:00–20:00", "wed": "08:00–20:00", "thu": "08:00–20:00", "fri": "08:00–20:00", "sat": "10:00–14:00", "sun": "10:00–14:00"},
    specialties: ["Dry needling", "Idrottsskador", "Huvudvärk"],
    paymentMethods: ["Friskvårdsbidrag"],
  },
  {
    slug: "naprapat-of-stockholm-ab",
    name: "Naprapat of Stockholm AB",
    city: "stockholm",
    neighborhood: "Kungsholmen",
    street: "Kungsgatan 84",
    postal: "112 27 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapat of Stockholm AB är en enpersonsklinik på Kungsgatan 84 i centrala Stockholm, driven av Frederic Neander med över 20 års erfarenhet. Kliniken är inriktad på naprapati kombinerat med funktionell neurologi.",
    rating: 4.9,
    reviewCount: 50,
    priceLevel: 2,
    bookingUrl: null,
    phone: "070-759 59 36",
    lat: 59.33116,
    lng: 18.04045,
    openingHours: {"mon": "07:00–17:00", "tue": "07:00–17:00", "wed": "07:00–17:00", "thu": "07:00–12:00", "fri": "07:00–12:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Nack- och ryggsmärta"],
  },
  {
    slug: "performance-center-lindhagen-naprapatklinik",
    name: "Performance Center Lindhagen - Naprapatklinik",
    city: "stockholm",
    neighborhood: "Kungsholmen",
    street: "Lindhagensgatan 135A",
    postal: "112 15 Stockholm",
    services: ["naprapat"],
    blurb: "Performance Center Lindhagen på Kungsholmen erbjuder naprapati, stötvågsbehandling, dry needling och rörelseanalys utförd av legitimerade naprapater. Kliniken är kombinerad med gym och personlig träning, vilket möjliggör ett samlat behandlings- och rehabupplägg.",
    rating: 4.9,
    reviewCount: 36,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/performance-center-lindhagen-1368",
    phone: "073-787 51 35",
    lat: 59.33293,
    lng: 18.03753,
    featured: true,
    openingHours: {"mon": "08:00–19:00", "tue": "08:00–19:00", "wed": "08:00–19:00", "thu": "08:00–19:00", "fri": "08:00–19:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Ischias", "Käkbesvär (TMD)", "Stötvågsbehandling", "Dry needling"],
  },
  {
    slug: "joylife-fysioterapi-naprapat-och-kiropraktor-fridhemsplan",
    name: "Joylife Fysioterapi, Naprapat & Kiropraktor Fridhemsplan",
    city: "stockholm",
    neighborhood: "Kungsholmen",
    street: "Sankt Eriksgatan 50",
    postal: "112 34 Stockholm",
    services: ["naprapat"],
    blurb: "Multidisciplinär klinik på Sankt Eriksgatan 50 inne på Nordic Wellness vid Fridhemsplan, med naprapater, kiropraktorer och fysioterapeuter under samma tak.",
    rating: 4.8,
    reviewCount: 123,
    priceLevel: 2,
    bookingUrl: null,
    phone: "070-6000 600",
    lat: 59.33292,
    lng: 18.04099,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–19:00"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta"],
    paymentMethods: ["Friskvårdsbidrag"],
    accessibility: ["Nära T-bana"],
  },
  {
    slug: "naprapaterna-kungsholmen",
    name: "Naprapaterna Kungsholmen",
    city: "stockholm",
    neighborhood: "Kungsholmen",
    street: "Kungsholmsgatan 32",
    postal: "112 27 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapaterna Kungsholmen är en naprapatklinik grundad 1994, belägen på Kungsholmsgatan 32 vid hörnet av Norra Agnegatan. Alla naprapater arbetar under Hälso- och sjukvårdslagen och är anslutna till Svenska Naprapatförbundet.",
    rating: 4.8,
    reviewCount: 34,
    priceLevel: 2,
    bookingUrl: "https://ww1.clinicbuddy.com/onlinebooking/-32?defaults%5Blocations%5D%5B%5D=1",
    phone: "08-650 74 30",
    lat: 59.33152,
    lng: 18.03828,
    featured: true,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–16:00"},
    established: 1994,
  },
  {
    slug: "nimm-nordiska-institutet-for-manuell-medicin",
    name: "NIMM - Nordiska Institutet för Manuell Medicin",
    city: "stockholm",
    neighborhood: "Norra Djurgården",
    street: "Kräftriket 23A",
    postal: "114 19 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "NIMM är ett av Nordens äldsta utbildningsinstitut inom manuell medicin, grundat 1970, med campus i Kräftriket och en studentdriven klinik i Vasastan (Observatoriegatan 17) där studenter behandlar patienter under handledning av legitimerade naprapater och kiropraktorer. Besökspriset är 375 kr, vilket speglar klinikens roll som utbildningsklinik.",
    rating: 4.8,
    reviewCount: 196,
    priceLevel: 1,
    bookingUrl: "https://www.nimm.se/klinik/boka-tid",
    phone: "08-31 19 19",
    lat: 59.36837,
    lng: 18.05218,
    featured: true,
    openingHours: {"mon": "09:00–16:00", "tue": "09:00–16:00", "wed": "09:00–16:00", "thu": "09:00–16:00", "fri": "09:00–16:00", "sat": "Stängt", "sun": "Stängt"},
  },
  {
    slug: "kroppex-norra-djurgardsstaden-naprapat",
    name: "Kroppex Norra Djurgårdsstaden - Naprapat",
    city: "stockholm",
    neighborhood: "Norra Djurgårdsstaden",
    street: "Bobergsgatan 57",
    postal: "115 47 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "Kroppex Norra Djurgårdsstaden på Bobergsgatan 57 är en naprapatklinik med öppettider även på helger. Kliniken drivs av den legitimerade naprapaten Henri Kallastu och har nära 1 000 betyg via Bokadirekt med ett snittbetyg på 4,9.",
    rating: 5.0,
    reviewCount: 59,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/kroppex-norra-djurgardsstaden-39929",
    phone: "08-744 30 94",
    lat: 59.34978,
    lng: 18.10298,
    featured: true,
    openingHours: {"mon": "13:00–19:00", "tue": "08:00–18:00", "wed": "13:00–19:00", "thu": "08:00–19:00", "fri": "13:00–18:00", "sat": "10:00–15:00", "sun": "09:00–15:00"},
    specialties: ["Löparskador", "Huvudvärk", "Nack- och ryggsmärta", "Dry needling", "Idrottsskador"],
    paymentMethods: ["Friskvårdsbidrag", "ePassi", "Benify"],
  },
  {
    slug: "stjarnkliniken-stockholm-city",
    name: "Stjärnkliniken Stockholm City",
    city: "stockholm",
    neighborhood: "Norrmalm",
    street: "Klarabergsviadukten 70",
    postal: "107 24 Stockholm",
    services: ["naprapat"],
    blurb: "Stjärnkliniken Stockholm City är belägen vid Klarabergsviadukten 70 (WTC) och erbjuder naprapati, fysioterapi och kiropraktik. Kliniken anlitas av svenska landslag och har legitimerade naprapater med inriktning mot idrottsskador och arbetsrelaterade besvär.",
    rating: 5.0,
    reviewCount: 211,
    priceLevel: 2,
    bookingUrl: "https://stjarnkliniken.app.myaimi.se/boka/stockholm-city",
    phone: "010-30 30 260",
    lat: 59.33554,
    lng: 18.06352,
    featured: true,
    openingHours: {"mon": "08:00–17:00", "tue": "08:00–17:00", "wed": "08:00–17:00", "thu": "08:00–17:00", "fri": "08:00–17:00", "sat": "10:00–14:00"},
    established: 2008,
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk", "Ischias"],
    accessibility: ["Nära T-bana", "Parkering"],
  },
  {
    slug: "naprawell-naprapat-stockholm-city",
    name: "NapraWell - Naprapat Stockholm City",
    city: "stockholm",
    neighborhood: "Norrmalm",
    street: "Kammakargatan 35a",
    postal: "111 60 Stockholm",
    services: ["naprapat"],
    blurb: "NapraWell är en naprapatklinik centralt belägen på Kammakargatan 35a i Stockholm City, ett par minuters promenad från Hötorget. Kliniken, med legitimerade naprapater, behandlar allt från akuta besvär och idrottsskador till långvariga smärttillstånd.",
    rating: 5.0,
    reviewCount: 41,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/naprawell-naprapat-stockholm-city-58366",
    phone: "08-296367",
    lat: 59.33542,
    lng: 18.06415,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–19:00", "sat": "10:00–14:00"},
    specialties: ["Nack- och ryggsmärta", "Huvudvärk", "Idrottsskador", "Löparskador", "Stötvågsbehandling", "Dry needling"],
    paymentMethods: ["Friskvårdsbidrag", "ePassi"],
  },
  {
    slug: "stockholms-rehabklinik-city",
    name: "Stockholms RehabKlinik CITY",
    city: "stockholm",
    neighborhood: "Norrmalm",
    street: "Kungsgatan 35",
    postal: "111 56 Stockholm",
    services: ["naprapat"],
    blurb: "Stockholms RehabKlinik CITY på Kungsgatan 35 grundades 2002 och erbjuder naprapati och fysioterapi i centrala Stockholm nära Hötorget. Kliniken samarbetar med flera försäkringsbolag och har sedan starten hjälpt närmare 23 000 patienter.",
    rating: 5.0,
    reviewCount: 29,
    priceLevel: 2,
    bookingUrl: "https://srkc.se/",
    phone: "08-640 00 60",
    lat: 59.33461,
    lng: 18.06537,
    featured: true,
    openingHours: {"mon": "08:00–19:00", "tue": "08:00–19:00", "wed": "08:00–19:00", "thu": "08:00–19:00", "fri": "08:00–19:00", "sat": "Stängt", "sun": "Stängt"},
    established: 2002,
    specialties: ["Nack- och ryggsmärta", "Huvudvärk", "Idrottsskador", "Stötvågsbehandling", "Dry needling"],
    paymentMethods: ["Kort", "Faktura"],
    accessibility: ["Hiss"],
  },
  {
    slug: "agilokliniken-naprapat-stockholm-city",
    name: "Agilokliniken - Naprapat Stockholm City",
    city: "stockholm",
    neighborhood: "Norrmalm",
    street: "Västra Järnvägsgatan 13",
    postal: "111 64 Stockholm",
    services: ["naprapat"],
    blurb: "Agilokliniken City är en väletablerad naprapatklinik på Västra Järnvägsgatan 13, ett par minuters promenad från Centralstationen. Kliniken har fem behandlingsrum och erbjuder naprapati, fysioterapi, stötvågsbehandling, laserbehandling och diagnostiskt ultraljud.",
    rating: 4.8,
    reviewCount: 66,
    priceLevel: 2,
    bookingUrl: "https://agilokliniken.se/boka-tid-naprapat/",
    phone: "08-21 99 29",
    lat: 59.33414,
    lng: 18.06326,
    featured: true,
    openingHours: {"mon": "07:00–18:40", "tue": "07:00–18:40", "wed": "08:00–18:50", "thu": "08:00–18:50", "fri": "07:00–15:10", "sat": "10:00–14:00"},
    established: 1991,
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Stötvågsbehandling", "Medicinsk akupunktur"],
  },
  {
    slug: "full-funktion-naprapatklinik",
    name: "Full Funktion - Naprapatklinik",
    city: "stockholm",
    neighborhood: "Norrmalm",
    street: "Tegnérgatan 51",
    postal: "111 61 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatklinik på Tegnérgatan 51 i Vasastan med legitimerade naprapater och tillverkning av ortopediska inläggssulor på plats.",
    rating: 4.8,
    reviewCount: 58,
    priceLevel: 2,
    bookingUrl: null,
    phone: "08-400 26 104",
    lat: 59.33549,
    lng: 18.06359,
    openingHours: {"mon": "08:00–20:00", "tue": "08:00–20:00", "wed": "08:00–20:00", "thu": "08:00–20:00", "fri": "08:00–19:00", "sat": "10:00–16:00", "sun": "11:00–17:00"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Ischias", "Whiplash", "Stötvågsbehandling", "Medicinsk akupunktur"],
  },
  {
    slug: "aktiv-halsa-naprapat-sollentuna-rackethall",
    name: "Aktiv Hälsa, Naprapat Sollentuna Rackethall",
    city: "stockholm",
    neighborhood: "Sollentuna",
    street: "Stubbhagsvägen 6",
    postal: "192 51 Sollentuna",
    services: ["naprapat"],
    blurb: "Aktiv Hälsa Naprapat Sollentuna Rackethall drivs av leg. naprapat Mats Larsson, examinerad 2006 och vidareutbildad inom idrottsmedicin vid Uppsala universitet. Kliniken erbjuder naprapati, massage, personlig träning och rehabilitering i Sollentuna Rackethalls lokaler.",
    rating: 5.0,
    reviewCount: 63,
    priceLevel: 2,
    bookingUrl: "https://naprapatsollentunarackethall.se/bokning/",
    phone: "073-969 33 87",
    lat: 59.42909,
    lng: 17.95039,
    featured: true,
    openingHours: {"mon": "08:00–17:00", "tue": "08:00–17:00", "wed": "08:00–17:00", "thu": "08:00–17:00", "fri": "08:00–16:00"},
    specialties: ["Idrottsskador", "Kontorsrelaterade besvär", "Nack- och ryggsmärta"],
  },
  {
    slug: "napractiva-naprapat-julian-sollentuna",
    name: "Napractiva - Naprapat Julian Sollentuna",
    city: "stockholm",
    neighborhood: "Sollentuna",
    street: "Aniaraplatsen 2",
    postal: "3tr, 191 47 Sollentuna",
    services: ["naprapat", "massor"],
    blurb: "Napractiva är en enpersonsklinik i Sollentuna driven av leg. naprapat Julian Benitez, med över 20 års klinisk erfarenhet och bakgrund som elitidrottare. Kliniken erbjuder individuellt anpassad naprapatbehandling, terapeutisk massage, idrottsmassage och akupunktur.",
    rating: 4.9,
    reviewCount: 56,
    priceLevel: 2,
    bookingUrl: null,
    phone: "073-101 31 41",
    lat: 59.42861,
    lng: 17.94773,
    openingHours: {"mon": "08:00–18:00", "tue": "08:00–18:00", "wed": "08:00–18:00", "thu": "08:00–18:00", "fri": "08:00–18:00"},
    specialties: ["Nack- och ryggsmärta", "Ischias", "Idrottsskador", "Medicinsk akupunktur"],
  },
  {
    slug: "naprapatgruppen-08-solna",
    name: "Naprapatgruppen 08 Solna",
    city: "stockholm",
    neighborhood: "Solna",
    street: "Greta Garbos väg 11",
    postal: "169 40 Solna",
    services: ["naprapat"],
    blurb: "Naprapatgruppen 08 Solna är en enmansdriven klinik i Gamla Råsunda (Greta Garbos väg 11) med leg. naprapat Karin Albinder Monteil, som har över 20 års klinisk erfarenhet och en specialisering inom kvinnohälsa och klimakteriebesvär utöver allmän naprapati och idrottsskador.",
    rating: 5.0,
    reviewCount: 213,
    priceLevel: 2,
    bookingUrl: "https://ww1.clinicbuddy.com/onlinebooking/-103?params%5Blocations%5D%5B%5D=4",
    phone: "070-413 33 26",
    lat: 59.35918,
    lng: 17.99895,
    featured: true,
    openingHours: {"mon": "08:00–19:00", "tue": "08:00–19:00", "wed": "08:00–19:00", "thu": "08:00–19:00", "fri": "08:00–17:00"},
    established: 2007,
    specialties: ["Nack- och ryggsmärta", "Idrottsskador", "Huvudvärk", "Kontorsrelaterade besvär"],
    paymentMethods: ["ePassi", "Benify"],
  },
  {
    slug: "kroppex-solna-naprapat",
    name: "Kroppex Solna - Naprapat",
    city: "stockholm",
    neighborhood: "Solna",
    street: "Johan Enbergs väg 20",
    postal: "171 61 Solna",
    services: ["naprapat", "massor"],
    blurb: "Kroppex Solna är beläget vid Johan Enbergs väg 20 i Västra Skogen, direkt vid tunnelbanan, och erbjuder naprapati, dry needling, akupunktur, idrottsmassage och träning. Kliniken ingår i Kroppex-kedjan med tre Stockholmsområdeskliniker.",
    rating: 5.0,
    reviewCount: 22,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/kroppex-solna-49310",
    phone: "08-744 30 94",
    lat: 59.35874,
    lng: 17.99866,
    specialties: ["Löparskador", "Huvudvärk", "Nack- och ryggsmärta", "Dry needling", "Idrottsskador"],
    paymentMethods: ["Friskvårdsbidrag", "ePassi", "Benify"],
  },
  {
    slug: "joylife-naprapati-chiropractic-and-massage",
    name: "Joylife Naprapati, Chiropractic and Massage",
    city: "stockholm",
    neighborhood: "Solna",
    street: "Dalvägen 24",
    postal: "169 79 Solna",
    services: ["naprapat", "massor"],
    blurb: "Joylife Solna är en multidisciplinär klinik vid Dalvägen 24 i Solna Business Park med ett team av legitimerade naprapater, kiropraktorer och fysioterapeuter. Kliniken använder modern diagnostik som ultraljud, laser och stötvågsbehandling och är en del av Joylife Healthcare AB, som beskriver sig som ett rikstäckande nätverk.",
    rating: 4.7,
    reviewCount: 127,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/profile-places/joylife-solna-129456",
    phone: "070-6000 600",
    lat: 59.3588,
    lng: 17.99889,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–19:00"},
    specialties: ["Kontorsrelaterade besvär", "Ischias", "Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk", "Stötvågsbehandling"],
    paymentMethods: ["Friskvårdsbidrag"],
  },
  {
    slug: "limbra-arenastaden",
    name: "Limbra Arenastaden",
    city: "stockholm",
    neighborhood: "Solna",
    street: "Evenemangsgatan 17",
    postal: "169 79 Solna",
    services: ["naprapat"],
    blurb: "Limbra Arenastaden (tidigare Naprapatlandslaget Arenastaden) är en klinik i Solna vid Evenemangsgatan 17, intill Mall of Scandinavia, med ett team av fyra legitimerade naprapater och två legitimerade fysioterapeuter. Kliniken ingår i Limbra-nätverket som samlar manual- och fysioterapeutiska kliniker nationellt.",
    rating: 4.6,
    reviewCount: 68,
    priceLevel: 3,
    bookingUrl: "https://limbra.se/kliniker/arenastaden/",
    phone: "010-768 10 30",
    lat: 59.36041,
    lng: 17.99932,
    featured: true,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–18:00", "sat": "10:00–15:00", "sun": "Stängt"},
    specialties: ["Kontorsrelaterade besvär", "Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk"],
    paymentMethods: ["Swish", "Kort"],
  },
  {
    slug: "muskelakuten-sundbyberg-naprapat-och-massage",
    name: "Muskelakuten Sundbyberg - Naprapat & Massage",
    city: "stockholm",
    neighborhood: "Sundbyberg",
    street: "Gjuteribacken 13",
    postal: "172 65 Sundbyberg",
    services: ["naprapat", "massor"],
    blurb: "Muskelakuten Sundbyberg är en klinik på Gjuteribacken 13 i Sundbyberg centrum med naprapati, massage och friskvårdsbehandling. Kliniken ingår i Muskelakuten FM AB och erbjuder behandling av akuta och kroniska muskel- och ledbesvär med bland annat klassisk massage, triggerpunktsbehandling och akupunktur.",
    rating: 4.9,
    reviewCount: 40,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/sundbyberg-muskelakuten-60517",
    phone: "070-974 63 20",
    lat: 59.36061,
    lng: 17.96955,
    specialties: ["Löparskador", "Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk"],
  },
  {
    slug: "sundbybergs-naprapat-och-ryggklinik",
    name: "Sundbybergs Naprapat & Ryggklinik",
    city: "stockholm",
    neighborhood: "Sundbyberg",
    street: "Trädgårdsgatan 26",
    postal: "172 38 Sundbyberg",
    services: ["naprapat", "massor"],
    blurb: "Sundbybergs Naprapat & Ryggklinik drivs sedan 2023 under varumärket NapraWell och är belägen på Trädgårdsgatan 26 i centrala Sundbyberg, etablerad på samma adress sedan 1986. Kliniken är en del av NapraWell-kedjan med legitimerade naprapater och erbjuder behandlingar med ledjusteringar, akupunktur och dry needling.",
    rating: 4.7,
    reviewCount: 68,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/naprawell-naprapat-sundbyberg-347",
    phone: "08-296367",
    lat: 59.3603,
    lng: 17.97318,
    featured: true,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–19:00", "sat": "10:00–14:00"},
    specialties: ["Nack- och ryggsmärta", "Ischias", "Huvudvärk", "Idrottsskador", "Graviditetsbesvär"],
  },
  {
    slug: "sundbybergs-halsocenter",
    name: "Sundbybergs Hälsocenter",
    city: "stockholm",
    neighborhood: "Sundbyberg",
    street: "Brunnsgatan 4A",
    postal: "172 68 Sundbyberg",
    services: ["naprapat", "massor"],
    blurb: "Sundbybergs Hälsocenter är en väletablerad klinik med rötter sedan 1998, belägen centralt i Sundbyberg. Kliniken erbjuder naprapatbehandling utförd av legitimerade naprapater samt massage, lymfmassage och stötvågsbehandling.",
    rating: 4.7,
    reviewCount: 59,
    priceLevel: 2,
    bookingUrl: "https://ww1.clinicbuddy.com/onlinebooking/Sundbybergs-H%C3%A4lsocenter-187",
    phone: "08-28 99 22",
    lat: 59.36144,
    lng: 17.97155,
    featured: true,
    established: 1998,
    specialties: ["Idrottsskador", "Barn & ungdom", "Löparskador", "Dry needling", "Medicinsk akupunktur"],
  },
  {
    slug: "stjarnkliniken-stockholm-soder",
    name: "Stjärnkliniken Stockholm Söder",
    city: "stockholm",
    neighborhood: "Södermalm",
    street: "Mariatorget 5",
    postal: "118 48 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "Stjärnkliniken Stockholm Söder är belägen vid Mariatorget 5 (i Saga Motion) på Södermalm och erbjuder naprapati, massage och rehabilitering med legitimerade naprapater. Kliniken är en del av Stjärnklinikenkedjan med samarbete med svenska landslag.",
    rating: 5.0,
    reviewCount: 99,
    priceLevel: 2,
    bookingUrl: "https://stjarnkliniken.app.myaimi.se/boka/stockholm-soder",
    phone: "010-30 30 260",
    lat: 59.31301,
    lng: 18.07115,
    openingHours: {"mon": "07:30–19:30", "tue": "07:30–19:30", "wed": "07:30–19:30", "thu": "07:30–19:30", "fri": "07:30–16:30", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk", "Stötvågsbehandling", "Dry needling"],
    paymentMethods: ["Friskvårdsbidrag"],
  },
  {
    slug: "optimal-rehab-sodermalm",
    name: "Optimal Rehab Södermalm",
    city: "stockholm",
    neighborhood: "Södermalm",
    street: "Lundagatan 57",
    postal: "117 29 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatklinik på Lundagatan 57 vid Hornstull på Södermalm. Behandlar akuta ryggskott och idrottsskador; nybesök kostar 780 kr och varar ca 45 minuter.",
    rating: 5.0,
    reviewCount: 34,
    priceLevel: 2,
    bookingUrl: "https://www.optimalrehab.se/boka-sodermalm/",
    phone: "08-502 503 68",
    lat: 59.31299,
    lng: 18.0694,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–19:00", "sat": "09:00–15:30", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk", "Dry needling"],
  },
  {
    slug: "athletic-medicine",
    name: "Athletic Medicine",
    city: "stockholm",
    neighborhood: "Södermalm",
    street: "Hornsgatan 74",
    postal: "118 21 Stockholm",
    services: ["naprapat"],
    blurb: "Athletic Medicine är en naprapatik- och träningsklinik på Hornsgatan 74 på Södermalm, driven av Björn Hermansson som är legitimerad naprapat med masterexamen. Kliniken är inriktad på idrottsmedicin och erbjuder naprapati, personlig träning och hälsoscreening.",
    rating: 5.0,
    reviewCount: 31,
    priceLevel: 2,
    bookingUrl: null,
    phone: "072 222 37 95",
    lat: 59.31547,
    lng: 18.0707,
    openingHours: {"mon": "08:00–17:00", "tue": "08:00–17:00", "wed": "08:00–17:00", "thu": "08:00–17:00", "fri": "08:00–17:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Löparskador"],
  },
  {
    slug: "camilla-westling-leg-naprapat-ab",
    name: "Camilla Westling Leg Naprapat AB",
    city: "stockholm",
    neighborhood: "Södermalm",
    street: "Götgatan 60",
    postal: "118 26 Stockholm",
    services: ["naprapat"],
    blurb: "Camilla Westling Leg Naprapat AB är en enpersonsklinik på Götgatan 60 på Södermalm, nära tunnelbanestationen Medborgarplatsen. Camilla Westling är legitimerad naprapat sedan 2001 och medlem i Svenska Naprapatförbundet.",
    rating: 4.9,
    reviewCount: 57,
    priceLevel: 2,
    bookingUrl: "https://naprapatwestling.bokamera.se/book",
    phone: "070-930 14 86",
    lat: 59.31417,
    lng: 18.07092,
    openingHours: {"mon": "Stängt", "tue": "Stängt", "wed": "Stängt", "thu": "07:30–16:00", "fri": "07:30–12:30", "sat": "09:00–15:00", "sun": "Stängt"},
  },
  {
    slug: "totalkropp-naprapat-peter-viklund",
    name: "Totalkropp / Naprapat Peter Viklund",
    city: "stockholm",
    neighborhood: "Södermalm",
    street: "Ingenjörsvägen 34",
    postal: "117 59 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatklinik i Liljeholmen på Ingenjörsvägen 34, grundad av Peter Viklund som även undervisar vid Naprapathögskolan och forskar om långvarig smärta vid Karolinska Institutet. Kliniken erbjuder naprapati, massage och specialiserad behandling av käkled.",
    rating: 4.8,
    reviewCount: 82,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/totalkropp-408",
    phone: "08-54 900 700",
    lat: 59.31503,
    lng: 18.07138,
    featured: true,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–19:00"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Käkbesvär (TMD)", "Graviditetsbesvär", "Barn & ungdom", "Stötvågsbehandling"],
    paymentMethods: ["Friskvårdsbidrag", "Benify", "Actiway", "Wellnet"],
  },
  {
    slug: "muskelakuten-sodermalm-hornstull-naprapat-och-massage",
    name: "Muskelakuten Södermalm/Hornstull - Naprapat & Massage",
    city: "stockholm",
    neighborhood: "Södermalm",
    street: "Lundagatan 57",
    postal: "117 28 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "Naprapatklinik vid Lundagatan 57 på Södermalm/Hornstull, del av Muskelakuten FM AB. Behandlar akuta och kroniska muskel- och ledbesvär samt erbjuder massage och ortopediska skoinlägg.",
    rating: 4.8,
    reviewCount: 70,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/sodermalm-hornstull-muskelakuten-55152",
    phone: "070-974 63 20",
    lat: 59.31319,
    lng: 18.06766,
    openingHours: {"mon": "06:00–21:00", "tue": "06:00–21:00", "wed": "06:00–21:00", "thu": "06:00–21:00", "fri": "06:00–21:00", "sat": "09:00–17:00", "sun": "09:00–17:00"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk", "Ischias", "Medicinsk akupunktur", "Dry needling"],
  },
  {
    slug: "limbra-hornstull",
    name: "Limbra Hornstull",
    city: "stockholm",
    neighborhood: "Södermalm",
    street: "Verkstadsgatan 2",
    postal: "117 28 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatklinik i Hornstull på Verkstadsgatan 2, tidigare Naprapatlandslaget Hornstull och numera del av Limbra-kedjan. Erbjuder individanpassad naprapatbehandling och rehabilitering för akuta och långvariga besvär.",
    rating: 4.8,
    reviewCount: 67,
    priceLevel: 2,
    bookingUrl: "https://limbra.se/kliniker/hornstull/",
    phone: "010-768 10 30",
    lat: 59.31345,
    lng: 18.06884,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–19:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk", "Ischias"],
    paymentMethods: ["Kort", "Swish"],
  },
  {
    slug: "limbra-sodermalm-sofo",
    name: "Limbra Södermalm SoFo",
    city: "stockholm",
    neighborhood: "Södermalm",
    street: "Kocksgatan 24",
    postal: "116 24 Stockholm",
    services: ["naprapat"],
    blurb: "Limbra Södermalm SoFo (tidigare Naprapatlandslaget Södermalm) är en naprapatklinik på Kocksgatan 24 i SoFo, ett par kvarter från Medborgarplatsen. Kliniken har sex legitimerade naprapater och behandlar allt från kontorsrelaterade besvär till idrottsskador.",
    rating: 4.7,
    reviewCount: 66,
    priceLevel: 2,
    bookingUrl: "https://limbra.se/kliniker/sodermalm/",
    phone: "010-768 10 30",
    lat: 59.31313,
    lng: 18.07221,
    openingHours: {"mon": "07:00–19:00", "tue": "07:00–19:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–19:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk", "Kontorsrelaterade besvär"],
    paymentMethods: ["Kort", "Swish"],
  },
  {
    slug: "naprapat-group-taby-centrum-ab",
    name: "Naprapat Group Täby Centrum AB",
    city: "stockholm",
    neighborhood: "Täby",
    street: "Stora Marknadsvägen 15",
    postal: "183 34 Täby",
    services: ["naprapat"],
    blurb: "Naprapatgruppen Täby Centrum är en naprapatklinik belägen i Täby Centrum med ett team av legitimerade naprapater, samtliga medlemmar i Svenska Naprapatförbundet. Utöver manuell behandling erbjuds stötvågsbehandling, diagnostisk ultraljud, laserbehandling och dry needling.",
    rating: 5.0,
    reviewCount: 280,
    priceLevel: 2,
    bookingUrl: "https://naprapatgruppentaby.bestille.no/OnCust2/",
    phone: "08-39 16 60",
    lat: 59.44513,
    lng: 18.06707,
    featured: true,
    openingHours: {"mon": "07:00–20:00", "tue": "07:00–18:00", "wed": "07:00–19:00", "thu": "07:00–19:00", "fri": "07:00–17:00", "sat": "09:00–15:30", "sun": "Stängt"},
    established: 2010,
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Huvudvärk", "Ischias", "Stötvågsbehandling", "Dry needling"],
    accessibility: ["Rullstolsanpassad"],
  },
  {
    slug: "roslagskliniken-naprapatklinik",
    name: "Roslagskliniken - Naprapatklinik",
    city: "stockholm",
    neighborhood: "Täby",
    street: "Eskadervägen 8",
    postal: "183 54 Täby",
    services: ["naprapat"],
    blurb: "Roslagskliniken är en naprapatklinik med idrottsmedicinsk inriktning i Näsby Park, Täby, verksam sedan 1980. Kliniken erbjuder manipulation, mobilisering, massage, dry needling, stötvågsbehandling och rehabilitering, samt ett eget gym för rehabträning.",
    rating: 5.0,
    reviewCount: 138,
    priceLevel: 2,
    bookingUrl: null,
    phone: "08-758 78 84",
    lat: 59.44447,
    lng: 18.06748,
    featured: true,
    openingHours: {"mon": "08:00–17:00", "tue": "08:00–17:00", "wed": "08:00–17:00", "thu": "08:00–17:00", "fri": "08:00–17:00", "sat": "Stängt", "sun": "Stängt"},
    established: 1980,
    specialties: ["Idrottsskador", "Löparskador", "Dry needling", "Stötvågsbehandling"],
  },
  {
    slug: "naprapatcenter-ab-taby",
    name: "Naprapatcenter AB Täby",
    city: "stockholm",
    neighborhood: "Täby",
    street: "Värtavägen 53",
    postal: "183 63 Täby",
    services: ["naprapat"],
    blurb: "Naprapatcenter AB Täby drivs av leg. naprapat Hamid Nafar med mer än 30 års erfarenhet. Kliniken är verksam kvällstid och helger i Viggbyholm och erbjuder naprapati kombinerat med ultraljudsdiagnostik, stötvåg, laser, akupunktur och rörelseanalys.",
    rating: 5.0,
    reviewCount: 55,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/naprapatcenter-ab-taby-49934",
    phone: "08-580 25 009",
    lat: 59.44524,
    lng: 18.06779,
    openingHours: {"mon": "07:30–19:30", "tue": "07:30–19:30", "wed": "07:30–19:30", "thu": "07:30–19:30", "fri": "07:30–16:30", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Stötvågsbehandling", "Medicinsk akupunktur"],
  },
  {
    slug: "omega-naprapati-naprapat-taby",
    name: "Omega Naprapati / Naprapat Täby",
    city: "stockholm",
    neighborhood: "Täby",
    street: "Bergtorpsvägen 43B",
    postal: "183 64 Täby",
    services: ["naprapat"],
    blurb: "Omega Naprapati är en enpersonsklinik i Täby driven av leg. naprapat David Benyamin, examinerad 2011 och certifierad inom stötvågsbehandling, laserterapi och muskuloskeletal ultraljudsdiagnostik. Kliniken erbjuder dessutom formgjutna fotinlägg och behandling via försäkring.",
    rating: 4.9,
    reviewCount: 55,
    priceLevel: 2,
    bookingUrl: null,
    phone: "08-446 10 80",
    lat: 59.44329,
    lng: 18.06673,
    featured: true,
    openingHours: {"mon": "08:00–17:30", "tue": "08:00–17:30", "wed": "08:00–17:30", "thu": "08:00–17:30", "fri": "10:00–14:30"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Stötvågsbehandling"],
  },
  {
    slug: "arninge-rehab-och-friskvard",
    name: "Arninge Rehab & Friskvård",
    city: "stockholm",
    neighborhood: "Täby",
    street: "Saluvägen 1",
    postal: "187 66 Täby",
    services: ["naprapat"],
    blurb: "Arninge Rehab & Friskvård är en bred klinik i Täby som erbjuder naprapati, massage och friskvård för privatpersoner och företag. Leg. naprapat Magnus Hård har 30 års erfarenhet och meriter från bland annat Svenska friidrottsförbundet och Djurgårdens IF.",
    rating: 4.9,
    reviewCount: 48,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/arninge-rehab-friskvard-5604",
    phone: "070-589 17 04",
    lat: 59.44418,
    lng: 18.06681,
    featured: true,
    openingHours: {"mon": "09:00–17:30", "tue": "09:00–19:00", "wed": "09:00–17:30", "thu": "09:00–18:00", "fri": "09:00–17:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Idrottsskador", "Käkbesvär (TMD)", "Kontorsrelaterade besvär", "Dry needling"],
    accessibility: ["Rullstolsanpassad"],
  },
  {
    slug: "kroppex-odenplan-naprapat",
    name: "Kroppex Odenplan - Naprapat",
    city: "stockholm",
    neighborhood: "Vasastan",
    street: "Odengatan 36",
    postal: "113 51 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatklinik vid Odenplan, Odengatan 36, med öppethållande alla dagar i veckan och online-bokning via Bokadirekt.",
    rating: 5.0,
    reviewCount: 157,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/kroppex-odenplan-29449",
    phone: "08-744 30 94",
    lat: 59.34525,
    lng: 18.04899,
    openingHours: {"mon": "07:30–18:30", "tue": "09:00–20:00", "wed": "07:00–20:00", "thu": "09:00–16:00", "fri": "07:00–20:00", "sat": "10:00–16:00", "sun": "10:00–17:00"},
    specialties: ["Löparskador", "Huvudvärk", "Dry needling"],
  },
  {
    slug: "city-naprapaterna",
    name: "City Naprapaterna",
    city: "stockholm",
    neighborhood: "Vasastan",
    street: "Västmannagatan 16",
    postal: "113 60 Stockholm",
    services: ["naprapat"],
    blurb: "Etablerad naprapatklinik i hjärtat av Vasastan på Västmannagatan 16, grundad 1985, med ett flertal legitimerade naprapater och bred erfarenhet av manuell behandling.",
    rating: 5.0,
    reviewCount: 143,
    priceLevel: 2,
    bookingUrl: null,
    phone: "08-30 60 79",
    lat: 59.3447,
    lng: 18.0456,
    featured: true,
    openingHours: {"mon": "07:00–20:00", "tue": "07:00–20:00", "wed": "07:00–20:00", "thu": "07:00–20:00", "fri": "07:00–17:00"},
    established: 1985,
    specialties: ["Nack- och ryggsmärta", "Idrottsskador", "Huvudvärk", "Ischias"],
  },
  {
    slug: "naprapat-magnus-olympiokliniken-vasastan",
    name: "Naprapat Magnus - Olympiokliniken - Vasastan",
    city: "stockholm",
    neighborhood: "Vasastan",
    street: "Upplandsgatan 71",
    postal: "113 28 Stockholm",
    services: ["naprapat"],
    blurb: "Solopraktik i Vasastan på Olympiokliniken, Upplandsgatan 71, med fokus på helkroppsbedömning och rörelsemönsteranalys. Behandlar bl.a. knäbesvär, rygg och nacke.",
    rating: 5.0,
    reviewCount: 82,
    priceLevel: 2,
    bookingUrl: "https://system.easypractice.net/book/naprapat-magnus",
    phone: "08-525 180 15",
    lat: 59.34649,
    lng: 18.04705,
    openingHours: {"mon": "08:00–19:00", "tue": "08:00–19:00", "wed": "08:00–19:00", "thu": "08:00–19:00", "fri": "08:00–17:00"},
    specialties: ["Nack- och ryggsmärta", "Idrottsskador", "Huvudvärk", "Löparskador"],
  },
  {
    slug: "behandling-a-o-naprapati",
    name: "Behandling A-Ö Naprapati",
    city: "stockholm",
    neighborhood: "Vasastan",
    street: "Odengatan 106",
    postal: "113 22 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatklinik på Odengatan 106 i Vasastan nära Sankt Eriksplan, med akuttider varje dag och kombination av naprapati, massage och personlig träning.",
    rating: 5.0,
    reviewCount: 75,
    priceLevel: 2,
    bookingUrl: null,
    phone: "073-229 50 03",
    lat: 59.34377,
    lng: 18.04474,
    openingHours: {"mon": "08:00–20:00", "tue": "08:00–20:00", "wed": "08:00–20:00", "thu": "08:00–20:00", "fri": "08:00–17:00"},
    specialties: ["Nack- och ryggsmärta", "Idrottsskador", "Huvudvärk", "Kontorsrelaterade besvär"],
    paymentMethods: ["Actiway", "ePassi", "Wellnet"],
  },
  {
    slug: "adam-kotknackare-naprapat-stockholm",
    name: "Adam Kotknackare - Naprapat Stockholm",
    city: "stockholm",
    neighborhood: "Vasastan",
    street: "Torsgatan 36",
    postal: "113 62 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatklinik i Vasastan på Torsgatan 36 med inriktning på manuell behandling av muskel- och ledbesvär. Kliniken är bland annat naprapat för Svenska Landslaget i padel.",
    rating: 4.9,
    reviewCount: 697,
    priceLevel: 2,
    bookingUrl: null,
    phone: "08-30 56 00",
    lat: 59.34383,
    lng: 18.04764,
    featured: true,
    openingHours: {"mon": "06:00–22:00", "tue": "06:00–22:00", "wed": "06:00–22:00", "thu": "06:00–22:00", "fri": "06:00–17:00", "sat": "09:00–14:00", "sun": "09:00–12:00"},
    specialties: ["Nack- och ryggsmärta", "Idrottsskador", "Whiplash", "Ischias", "Löparskador"],
    paymentMethods: ["ePassi", "Wellnet"],
  },
  {
    slug: "limbra-odenplan",
    name: "Limbra Odenplan",
    city: "stockholm",
    neighborhood: "Vasastan",
    street: "Norrtullsgatan 4",
    postal: "113 29 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatklinik vid Odenplan, Norrtullsgatan 4, tidigare Naprapatlandslaget Odenplan, nu en del av Limbra-kedjan, med fem legitimerade naprapater.",
    rating: 4.7,
    reviewCount: 46,
    priceLevel: 3,
    bookingUrl: null,
    phone: "010-768 10 30",
    lat: 59.34588,
    lng: 18.04661,
    openingHours: {"mon": "07:00–20:00", "tue": "07:00–20:00", "wed": "07:00–20:00", "thu": "07:00–20:00", "fri": "07:00–18:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Nack- och ryggsmärta", "Idrottsskador", "Huvudvärk", "Kontorsrelaterade besvär"],
    paymentMethods: ["Kort", "Swish"],
  },
  {
    slug: "sabbatsbergs-ryggcentrum-naprapat-stockholm",
    name: "Sabbatsbergs Ryggcentrum Naprapat Stockholm",
    city: "stockholm",
    neighborhood: "Vasastan",
    street: "Dalagatan 9B",
    postal: "113 61 Stockholm",
    services: ["naprapat"],
    blurb: "Klinik på Dalagatan 9B vid Sabbatsbergs sjukhusområde med inriktning på ortopedisk manuell terapi och medicinsk fotvård, ansluten till Region Stockholm.",
    rating: 4.6,
    reviewCount: 47,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/sabbatsbergs-fot-och-ryggcentrum-fysioterapi-fotvard-hembesok-friskvard-massage-lordagsoppet-3934",
    phone: "08-31 21 32",
    lat: 59.34369,
    lng: 18.04641,
    openingHours: {"mon": "08:00–17:00", "tue": "08:00–17:00", "wed": "08:00–17:00", "thu": "08:00–17:00", "fri": "08:00–17:00"},
    specialties: ["Nack- och ryggsmärta", "Dry needling", "Medicinsk akupunktur"],
    paymentMethods: ["ePassi", "Wellnet"],
  },
  {
    slug: "naprapatmastarna-naprapat-ostermalm-stockholm",
    name: "NAPRAPATMÄSTARNA – Naprapat Östermalm Stockholm",
    city: "stockholm",
    neighborhood: "Östermalm",
    street: "Sturegatan 34",
    postal: "Våning 1, 114 36 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "Naprapatklinik nära Stureplan på Sturegatan 34 på Östermalm. Erbjuder naprapati, massage och sportmassage med individuell behandlingsplan; kliniken anger att de arbetar med legitimerade naprapater.",
    rating: 5.0,
    reviewCount: 49,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/naprapatmastarna-49273",
    phone: "073-627 02 49",
    lat: 59.34149,
    lng: 18.08115,
    openingHours: {"mon": "07:00–20:00", "tue": "07:00–20:00", "wed": "07:00–20:00", "thu": "07:00–20:00", "fri": "07:00–20:00", "sat": "10:00–16:00", "sun": "10:00–16:00"},
    specialties: ["Idrottsskador", "Nack- och ryggsmärta", "Ischias", "Stötvågsbehandling", "Dry needling", "Medicinsk akupunktur"],
    paymentMethods: ["ePassi", "Wellnet"],
  },
  {
    slug: "stjarnkliniken-stockholm-stureplan",
    name: "Stjärnkliniken Stockholm Stureplan",
    city: "stockholm",
    neighborhood: "Östermalm",
    street: "Sturegatan 16",
    postal: "114 36 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "Stjärnkliniken Stureplan på Sturegatan 16 är en del av Stjärnkliniken-kedjan med kliniker i flera svenska städer. Kliniken erbjuder legitimerade naprapater med specialisering inom naprapati, stötvågsbehandling och dry needling, och har samarbetat med svenska landslag.",
    rating: 5.0,
    reviewCount: 44,
    priceLevel: 3,
    bookingUrl: "https://stjarnkliniken.app.myaimi.se/boka/stockholm-stureplan",
    phone: "010-30 30 260",
    lat: 59.34141,
    lng: 18.0828,
    featured: true,
    openingHours: {"mon": "08:00–17:00", "tue": "08:00–17:00", "wed": "08:00–17:00", "thu": "08:00–17:00", "fri": "08:00–17:00"},
    specialties: ["Nack- och ryggsmärta", "Huvudvärk", "Ischias", "Idrottsskador", "Stötvågsbehandling"],
    paymentMethods: ["Friskvårdsbidrag"],
  },
  {
    slug: "napraparty",
    name: "Napraparty",
    city: "stockholm",
    neighborhood: "Östermalm",
    street: "Nybrogatan 71",
    postal: "114 40 Stockholm",
    services: ["naprapat"],
    blurb: "Napraparty är en enpersonsklinik på Nybrogatan 71 på Östermalm. Kliniken drivs av en naprapat som vid tidpunkten för kontroll var sjukskriven och förväntade återkomst i juli.",
    rating: 5.0,
    reviewCount: 36,
    priceLevel: 3,
    bookingUrl: "https://www.napraparty.se/bokning",
    phone: "0706 615 627",
    lat: 59.33853,
    lng: 18.0821,
    openingHours: {"mon": "08:30–17:30", "tue": "07:00–14:30", "wed": "08:30–18:00", "thu": "07:00–14:00", "fri": "08:30–14:00", "sat": "Stängt", "sun": "Stängt"},
    paymentMethods: ["Swish", "Faktura"],
  },
  {
    slug: "limbra-ostermalm",
    name: "Limbra Östermalm",
    city: "stockholm",
    neighborhood: "Östermalm",
    street: "Sturegatan 64",
    postal: "114 31 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "Limbra Östermalm på Sturegatan 64 är en del av Limbra AB, som samlar de tidigare kedjorna Naprapatlandslaget, Muskelcentrum och The Clinic under ett gemensamt varumärke. Kliniken erbjuder naprapati, kiropraktik, fysioterapi och massage.",
    rating: 5.0,
    reviewCount: 34,
    priceLevel: 2,
    bookingUrl: "https://limbra.se/city/stockholm/",
    phone: "010-768 10 30",
    lat: 59.34055,
    lng: 18.08118,
    openingHours: {"mon": "07:00–18:00", "tue": "07:00–18:00", "wed": "07:00–18:00", "thu": "07:00–18:00", "fri": "07:00–18:00", "sat": "Stängt", "sun": "Stängt"},
    specialties: ["Nack- och ryggsmärta", "Idrottsskador"],
    paymentMethods: ["Kort", "Swish"],
    accessibility: ["Nära T-bana", "Parkering"],
  },
  {
    slug: "naprapatiska-institutet-ostermalm",
    name: "Naprapatiska Institutet Östermalm",
    city: "stockholm",
    neighborhood: "Östermalm",
    street: "Tyskbagargatan 4",
    postal: "114 43 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatiska Institutet Östermalm är en del av en kedja med sju kliniker i Stockholmsregionen. Naprapaterna är legitimerade av Socialstyrelsen och erbjuder behandlingar inom bland annat idrottsmedicin, dry needling och stressrelaterade besvär.",
    rating: 5.0,
    reviewCount: 33,
    priceLevel: 2,
    bookingUrl: null,
    phone: "08-640 33 80",
    lat: 59.3393,
    lng: 18.0817,
    featured: true,
    openingHours: {"mon": "07:00–20:00", "tue": "07:00–20:00", "wed": "07:00–20:00", "thu": "07:00–20:00", "fri": "07:00–20:00"},
    accessibility: ["Nära T-bana"],
  },
  {
    slug: "naprapatstudion",
    name: "Naprapatstudion",
    city: "stockholm",
    neighborhood: "Östermalm",
    street: "Engelbrektsgatan 35B",
    postal: "114 32 Stockholm",
    services: ["naprapat"],
    blurb: "Naprapatstudion vid Tekniska högskolan på Östermalm drivs av de legitimerade naprapaterna Sandra Almgren och Ida Anstey, båda med över tio års yrkeserfarenhet. Kliniken erbjuder naprapati, massage, medicinsk laserbehandling, dry needling och specialiserad gravidbehandling.",
    rating: 5.0,
    reviewCount: 31,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/naprapatstudion-ida-anstey-26385",
    phone: "",
    lat: 59.33883,
    lng: 18.08067,
    featured: true,
    openingHours: {"mon": "13:00–19:30", "tue": "07:30–14:00", "wed": "07:30–14:00", "thu": "10:00–18:30", "fri": "07:00–15:00"},
    specialties: ["Graviditetsbesvär", "Dry needling"],
  },
  {
    slug: "sturenaprapaten-ab",
    name: "StureNaprapaten AB",
    city: "stockholm",
    neighborhood: "Östermalm",
    street: "Birger Jarlsgatan 34",
    postal: "114 29 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "StureNaprapaten är en naprapatklinik på Birger Jarlsgatan 34, nära Stureplan, med verksamhet sedan 2015. Kliniken erbjuder naprapati, massage och stötvågsbehandling med individuellt anpassade behandlingsplaner.",
    rating: 4.9,
    reviewCount: 138,
    priceLevel: 3,
    bookingUrl: "https://www.bokadirekt.se/places/sturenaprapaten-ab-10317",
    phone: "08-440 73 37",
    lat: 59.33986,
    lng: 18.08327,
    openingHours: {"mon": "07:30–20:00", "tue": "07:30–20:00", "wed": "07:30–20:00", "thu": "07:30–20:00", "fri": "07:30–17:00", "sat": "10:00–16:00", "sun": "10:00–16:00"},
    established: 2015,
    specialties: ["Nack- och ryggsmärta", "Idrottsskador", "Stötvågsbehandling", "Dry needling"],
    paymentMethods: ["Friskvårdsbidrag"],
  },
  {
    slug: "muskelakuten-ostermalm-naprapat-och-massage",
    name: "Muskelakuten Östermalm - Naprapat & Massage",
    city: "stockholm",
    neighborhood: "Östermalm",
    street: "Grev Turegatan 35",
    postal: "114 47 Stockholm",
    services: ["naprapat", "massor"],
    blurb: "Naprapatklinik på Grev Turegatan 35 på Östermalm, del av Muskelakuten FM AB. Naprapat Tom Gustafsson tar emot för naprapati, massage och ortopediska skoinlägg med inriktning på rygg-, nacke- och idrottsrelaterade besvär.",
    rating: 4.9,
    reviewCount: 28,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/ostermalm-muskelakuten-129466",
    phone: "073-080 56 07",
    lat: 59.34113,
    lng: 18.07982,
    openingHours: {"mon": "05:30–21:30", "tue": "05:30–21:30", "wed": "05:30–21:30", "thu": "05:30–21:30", "fri": "05:30–21:30", "sat": "Stängt", "sun": "08:30–16:30"},
    specialties: ["Nack- och ryggsmärta", "Huvudvärk", "Idrottsskador", "Löparskador"],
  },
  {
    slug: "arena-med-naprapat-goteborg",
    name: "Arena MED - Naprapat Göteborg",
    city: "goteborg",
    neighborhood: "Lorensberg",
    street: "Kungsportsavenyen 3",
    postal: "411 36 Göteborg",
    services: ["naprapat"],
    blurb: "Naprapatklinik på Avenyn grundad av Anders Gullberg, legitimerad naprapat, med tidsbokning via Bokadirekt.",
    rating: 5.0,
    reviewCount: 190,
    priceLevel: 3,
    bookingUrl: "https://www.bokadirekt.se/places/arena-med-50462",
    phone: "+46 31 18 80 11",
    lat: 57.7013,
    lng: 11.9731,
    featured: true,
    updatedAt: "2026-07-02",
  },
  {
    slug: "city-kliniken-naprapat-goteborg",
    name: "City-Kliniken - Naprapat Göteborg",
    city: "goteborg",
    neighborhood: "Inom Vallgraven",
    street: "Östra Hamngatan 52",
    postal: "411 09 Göteborg",
    services: ["naprapat"],
    blurb: "Naprapatklinik i city sedan 1994 med flera legitimerade naprapater; erbjuder även massage och rehabiliteringsträning.",
    rating: 5.0,
    reviewCount: 135,
    priceLevel: 2,
    bookingUrl: "https://napcitygoteborg.bestille.no/OnCust2/",
    phone: "",
    lat: 57.7048,
    lng: 11.9695,
    featured: true,
    updatedAt: "2026-07-02",
  },
  {
    slug: "ryggakuten-centrum",
    name: "RyggAkuten Centrum",
    city: "goteborg",
    neighborhood: "Inom Vallgraven",
    street: "Norra Hamngatan 18",
    postal: "411 06 Göteborg",
    services: ["naprapat", "kiropraktor"],
    blurb: "Naprapat- och kiropraktorklinik i Brunnsparken sedan 1992, med legitimerad naprapat Erika Larsson i teamet.",
    rating: 4.8,
    reviewCount: 81,
    priceLevel: 2,
    bookingUrl: "https://ryggakuten.com/bokning/",
    phone: "+46 31 152085",
    lat: 57.7074,
    lng: 11.9684,
    featured: true,
    updatedAt: "2026-07-02",
  },
  {
    slug: "eriksbergs-halsoklinik",
    name: "Eriksbergs Hälsoklinik",
    city: "goteborg",
    neighborhood: "Eriksberg",
    street: "Sjöporten 4",
    postal: "417 64 Göteborg",
    services: ["naprapat"],
    blurb: "Multidisciplinär hälsoklinik i Eriksberg där en legitimerad naprapat erbjuder behandling av rygg, nacke och leder bland flera terapiformer.",
    rating: 4.7,
    reviewCount: 107,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/eriksbergs-halsoklinik-12294",
    phone: "+46 73 528 61 08",
    lat: 57.7012,
    lng: 11.9156,
    featured: true,
    updatedAt: "2026-07-02",
  },
  {
    slug: "naprapatkliniken-vast-ab",
    name: "Naprapatkliniken Väst AB",
    city: "goteborg",
    neighborhood: "Askim",
    street: "Ekonomivägen 6",
    postal: "436 33 Göteborg",
    services: ["naprapat"],
    blurb: "Tvärprofessionell klinik i Askim sedan 1999 med flera legitimerade naprapater samt fysioterapeut och massageterapeuter.",
    rating: 4.7,
    reviewCount: 68,
    priceLevel: 2,
    bookingUrl: "https://www.naprapatklinikenvast.se/boka/",
    phone: "+46 31 68 35 70",
    lat: 57.6404,
    lng: 11.9469,
    featured: true,
    updatedAt: "2026-07-02",
  },
  {
    slug: "rygg-och-ledkliniken-i-goteborg",
    name: "Rygg och Ledkliniken i Göteborg",
    city: "goteborg",
    neighborhood: "Lorensberg",
    street: "Viktor Rydbergsgatan 10",
    postal: "411 32 Göteborg",
    services: ["naprapat"],
    blurb: "Naprapatklinik centralt vid Viktor Rydbergsgatan, bemannad av legitimerade naprapater för privatpersoner och idrottare.",
    rating: 5.0,
    reviewCount: 45,
    priceLevel: 2,
    bookingUrl: "https://www.ryggochled.se/goteborg/",
    phone: "+46 31 403033",
    lat: 57.6955,
    lng: 11.9773,
    updatedAt: "2026-07-02",
  },
  {
    slug: "smartcentralen-naprapat-goteborg",
    name: "Smärtcentralen - Naprapat Göteborg",
    city: "goteborg",
    neighborhood: "Eriksberg",
    street: "Sjöporten 4",
    postal: "417 64 Göteborg",
    services: ["naprapat"],
    blurb: "Naprapatklinik på Hisingen/Eriksberg, delar lokal med Eriksbergs Hälsoklinik; legitimerad naprapat Magnus Axelsson.",
    rating: 5.0,
    reviewCount: 37,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/eriksbergs-halsoklinik-12294",
    phone: "+46 73 528 61 08",
    lat: 57.7015,
    lng: 11.9151,
    updatedAt: "2026-07-02",
  },
  {
    slug: "aktiv-halsa",
    name: "Aktiv Hälsa",
    city: "goteborg",
    neighborhood: "Inom Vallgraven",
    street: "Otterhällegatan 2",
    postal: "411 18 Göteborg",
    services: ["naprapat"],
    blurb: "Naprapatklinik vid Lilla Torget med flera legitimerade naprapater, samarbete med ortoped och idrottspsykolog.",
    rating: 5.0,
    reviewCount: 25,
    priceLevel: 2,
    bookingUrl: "https://aktivhalsagbg.com/",
    phone: "+46 72 220 90 98",
    lat: 57.7051,
    lng: 11.9614,
    updatedAt: "2026-07-02",
  },
  {
    slug: "idrottsnaprapaten-ab",
    name: "Idrottsnaprapaten AB",
    city: "goteborg",
    neighborhood: "Linné",
    street: "Västergatan 4B",
    postal: "411 23 Göteborg",
    services: ["naprapat", "kiropraktor"],
    blurb: "Klinik med två legitimerade naprapater och en legitimerad kiropraktor, inriktad mot idrottsrelaterade besvär i Linné.",
    rating: 5.0,
    reviewCount: 22,
    priceLevel: 2,
    bookingUrl: "https://idrottsnaprapaten.se/boka-tid",
    phone: "",
    lat: 57.6951,
    lng: 11.9622,
    updatedAt: "2026-07-02",
  },
  {
    slug: "eva-rytterlund-leg-naprapat",
    name: "Eva Rytterlund Leg. Naprapat",
    city: "goteborg",
    neighborhood: "Lorensberg",
    street: "Wadmansgatan 9",
    postal: "412 53 Göteborg",
    services: ["naprapat"],
    blurb: "Egen mottagning sedan 2015, drivs av naprapat med examen 2001 och mångårig erfarenhet, tidigare medgrundare av Ullevikliniken.",
    rating: 5.0,
    reviewCount: 18,
    priceLevel: 2,
    bookingUrl: "https://ww1.clinicbuddy.com/onlinebooking/EvaRytterlund-2666",
    phone: "+46 706 26 91 35",
    lat: 57.6995,
    lng: 11.9819,
    updatedAt: "2026-07-02",
  },
  {
    slug: "care-of-spine-naprapatklinik",
    name: "Care of Spine - Naprapatklinik",
    city: "goteborg",
    neighborhood: "Linné",
    street: "Västergatan 4B",
    postal: "411 23 Göteborg",
    services: ["naprapat"],
    blurb: "Naprapatklinik i Linné, legitimerad naprapat sedan 2019, egen bokningskalender direkt via hemsidan.",
    rating: 5.0,
    reviewCount: 14,
    priceLevel: 2,
    bookingUrl: "https://careofspine.se/boka-tid/",
    phone: "",
    lat: 57.6951,
    lng: 11.9622,
    updatedAt: "2026-07-02",
  },
  {
    slug: "ryggplus-naprapatklinik",
    name: "Ryggplus Naprapatklinik",
    city: "goteborg",
    neighborhood: "Långedrag",
    street: "Långedragsvägen 48",
    postal: "426 71 Göteborg",
    services: ["naprapat"],
    blurb: "Enmansklinik i Västra Frölunda driven av legitimerad naprapat med examen från Naprapathögskolan, verksam sedan 1999.",
    rating: 5.0,
    reviewCount: 10,
    priceLevel: 2,
    bookingUrl: "https://www.ryggplus.se/boka-tid/",
    phone: "+46 703 10 44 33",
    lat: 57.6784,
    lng: 11.894,
    updatedAt: "2026-07-02",
  },
  {
    slug: "bodycheck-ab-naprapat-goteborg",
    name: "Bodycheck AB - Naprapat Göteborg",
    city: "goteborg",
    neighborhood: "Vasastan",
    street: "Erik Dahlbergsgatan 14",
    postal: "411 26 Göteborg",
    services: ["naprapat"],
    blurb: "Idrottsskadeklinik med naprapat Nicklas Wiltman, legitimerad 2008, inriktad mot idrottsskador, stötvåg och dry needling.",
    rating: 4.9,
    reviewCount: 18,
    priceLevel: 2,
    bookingUrl: "https://idrottsskadeexperten.se/boka-tid/",
    phone: "+46 770 17 50 51",
    lat: 57.6988,
    lng: 11.9683,
    updatedAt: "2026-07-02",
  },
  {
    slug: "ullevikliniken",
    name: "UlleviKliniken",
    city: "goteborg",
    neighborhood: "Ullevi",
    street: "Eva Rodhes Gata 8",
    postal: "411 11 Göteborg",
    services: ["naprapat", "massor"],
    blurb: "Naprapatmottagning nära Centralstationen och Ullevi med legitimerad naprapat Sylvia Lorentsson, verksam på plats sedan 2003.",
    rating: 4.8,
    reviewCount: 58,
    priceLevel: 2,
    bookingUrl: "https://ullevikliniken.se/naprapat/",
    phone: "",
    lat: 57.7083,
    lng: 11.9795,
    updatedAt: "2026-07-02",
  },
  {
    slug: "ryggakuten-sisjon",
    name: "RyggAkuten Sisjön",
    city: "goteborg",
    neighborhood: "Sisjön",
    street: "Datavägen 14B",
    postal: "436 32 Göteborg",
    services: ["naprapat", "kiropraktor"],
    blurb: "Naprapatklinik i Sisjön med legitimerade naprapater Martina Gunnarsson och Emil Amberntsson sedan flera år.",
    rating: 4.8,
    reviewCount: 28,
    priceLevel: 2,
    bookingUrl: "https://ryggakuten.com/bokning/",
    phone: "+46 31 845200",
    lat: 57.6395,
    lng: 11.957,
    updatedAt: "2026-07-02",
  },
  {
    slug: "ryggakuten-hisingen",
    name: "RyggAkuten Hisingen",
    city: "goteborg",
    neighborhood: "Lundby",
    street: "Hisingsgatan 28",
    postal: "417 03 Göteborg",
    services: ["naprapat", "kiropraktor"],
    blurb: "Naprapatmottagning på Hisingen med legitimerad naprapat Emil Andersson och kiropraktor Joakim Karlsson.",
    rating: 4.7,
    reviewCount: 64,
    priceLevel: 2,
    bookingUrl: "https://ryggakuten.com/bokning/",
    phone: "+46 31 234172",
    lat: 57.7191,
    lng: 11.9448,
    updatedAt: "2026-07-02",
  },
  {
    slug: "limbra-goteborg-vasastan",
    name: "Limbra Göteborg Vasastan",
    city: "goteborg",
    neighborhood: "Vasastan",
    street: "Aschebergsgatan 25",
    postal: "411 33 Göteborg",
    services: ["naprapat", "kiropraktor"],
    blurb: "Tvärvetenskaplig klinik i Limbra-kedjan (f.d. Naprapatlandslaget) med legitimerade naprapater och kiropraktor på plats.",
    rating: 4.7,
    reviewCount: 23,
    priceLevel: 3,
    bookingUrl: "https://limbra.se/kliniker/goteborg-vasastan/",
    phone: "",
    lat: 57.696,
    lng: 11.9711,
    updatedAt: "2026-07-02",
  },
  {
    slug: "goteborgs-naprapat-och-idrottsskadeklinik-ab",
    name: "Göteborgs Naprapat & Idrottsskadeklinik AB",
    city: "goteborg",
    neighborhood: "Heden",
    street: "Parkgatan 17",
    postal: "411 38 Göteborg",
    services: ["naprapat"],
    blurb: "Naprapatklinik med idrottsskadeinriktning, medlem i Svenska Naprapatförbundet, erbjuder rabatterat pris för studenter.",
    rating: 4.6,
    reviewCount: 30,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/goteborgs-naprapat-idrottsskadeklinik",
    phone: "",
    lat: 57.7005,
    lng: 11.9693,
    updatedAt: "2026-07-02",
  },
  {
    slug: "linus-och-marie-nilsson-leg-naprapater-ab",
    name: "Linus & Marie Nilsson Leg. Naprapater AB",
    city: "goteborg",
    neighborhood: "Askim",
    street: "Stora Åvägen 21",
    postal: "436 34 Göteborg",
    services: ["naprapat"],
    blurb: "Enskild klinik i Sisjön/Askim med två legitimerade naprapater, verksamma sedan 1999, över 25 års samlad erfarenhet.",
    rating: 4.5,
    reviewCount: 8,
    priceLevel: 2,
    bookingUrl: null,
    phone: "+46 31 68 59 00",
    lat: 57.6411,
    lng: 11.9576,
    updatedAt: "2026-07-02",
  },
  {
    slug: "akuta-ryggjouren",
    name: "Akuta Ryggjouren",
    city: "goteborg",
    neighborhood: "Vasastan",
    street: "Föreningsgatan 1A",
    postal: "411 27 Göteborg",
    services: ["naprapat"],
    blurb: "Akutinriktad naprapatmottagning i Vasastan sedan tidigt 1990-tal, drivs av legitimerad naprapat med examen 2001.",
    rating: 4.5,
    reviewCount: 6,
    priceLevel: 2,
    bookingUrl: "https://www.bokadirekt.se/places/akuta-ryggjouren-veronica-skanberg-130231",
    phone: "+46 31 82 85 60",
    lat: 57.6944,
    lng: 11.9616,
    updatedAt: "2026-07-02",
  },
  {
    slug: "limbra-goteborg-nordstan",
    name: "Limbra Göteborg Nordstan",
    city: "goteborg",
    neighborhood: "Nordstan",
    street: "Östra Hamngatan 17",
    postal: "411 10 Göteborg",
    services: ["naprapat"],
    blurb: "Multiterapeutklinik i Regus kontorshotell nära Nordstan med leg. naprapater, fysioterapeuter och kiropraktorer, del av Limbra-kedjan.",
    rating: 4.5,
    reviewCount: 5,
    priceLevel: 2,
    bookingUrl: "https://limbra.se/kliniker/goteborg-nordstan/",
    phone: "+46 10 768 10 30",
    lat: 57.7084,
    lng: 11.9668,
    updatedAt: "2026-07-02",
  },
];

export function getCity(slug: string): City | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getClinicsByCity(city: CitySlug, service: ServiceSlug): Clinic[] {
  return clinics
    .filter((c) => c.city === city && c.services.includes(service))
    .sort((a, b) => {
      if (a.featured && !b.featured) return -1;
      if (!a.featured && b.featured) return 1;
      return b.rating - a.rating;
    });
}

export function getClinicBySlug(city: CitySlug, slug: string): Clinic | undefined {
  return clinics.find((c) => c.city === city && c.slug === slug);
}

// Sibling clinics in the same neighborhood, excluding the current one. Used
// on detail pages for the "Fler kliniker i stadsdelen" rail.
export function getRelatedClinics(clinic: Clinic, limit = 3): Clinic[] {
  return clinics
    .filter(
      (c) =>
        c.city === clinic.city &&
        c.slug !== clinic.slug &&
        (c.neighborhood === clinic.neighborhood ||
          c.services.some((s) => clinic.services.includes(s))),
    )
    .sort((a, b) => {
      // Same-neighborhood first, then by rating.
      const aSame = a.neighborhood === clinic.neighborhood ? 1 : 0;
      const bSame = b.neighborhood === clinic.neighborhood ? 1 : 0;
      if (aSame !== bSame) return bSame - aSame;
      return b.rating - a.rating;
    })
    .slice(0, limit);
}

// Total clinics per city across ALL services in the seed data.
// Used for homepage city cards so the count reflects the actual dataset
// (later: swap for a `select count(*)` when clinics move to Lovable Cloud).
export function getCityClinicCount(city: CitySlug): number {
  return clinics.filter((c) => c.city === city).length;
}

export interface PriceLevelInfo {
  label: string;
  range: string;
  dots: string;
}

export const priceLevelInfo: Record<1 | 2 | 3, PriceLevelInfo> = {
  1: { label: "Budget", range: "ca 400–650 kr", dots: "●" },
  2: { label: "Standard", range: "ca 650–900 kr", dots: "●●" },
  3: { label: "Premium", range: "ca 900+ kr", dots: "●●●" },
};

export function getPriceLevelInfo(level: number): PriceLevelInfo {
  const key = level as 1 | 2 | 3;
  return priceLevelInfo[key] ?? priceLevelInfo[2];
}

export function priceLabel(level: 1 | 2 | 3): string {
  return priceLevelInfo[level].label;
}

// ─────────────────────────────────────────────────────────────────────────────
// Editorial enrichment helpers — used to render rich, LLM-friendly detail
// pages even when per-clinic enrichment fields (openingHours, specialties,
// etc.) are missing. Content is evergreen and generic where clinic-specific
// data isn't available; extraction-friendly Q&A for FAQPage schema.
// ─────────────────────────────────────────────────────────────────────────────

export const weekdayLabels: Record<
  "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun",
  { short: string; long: string; schema: string }
> = {
  mon: { short: "Mån", long: "Måndag", schema: "Monday" },
  tue: { short: "Tis", long: "Tisdag", schema: "Tuesday" },
  wed: { short: "Ons", long: "Onsdag", schema: "Wednesday" },
  thu: { short: "Tor", long: "Torsdag", schema: "Thursday" },
  fri: { short: "Fre", long: "Fredag", schema: "Friday" },
  sat: { short: "Lör", long: "Lördag", schema: "Saturday" },
  sun: { short: "Sön", long: "Söndag", schema: "Sunday" },
};

// Editorial descriptions per treatment form. Extraction-optimized for LLMs:
// title + short definition + typical use case.
export const treatmentDescriptions: Record<
  ServiceSlug,
  { title: string; description: string; treats: string[] }
> = {
  naprapat: {
    title: "Naprapati",
    description:
      "Naprapati är en manuell behandlingsform som fokuserar på att återställa funktion i rörelse- och stödjeorganen. Behandlingen kombinerar ledmobilisering, manipulation, muskeltöjning och stretching med råd om träning och ergonomi. Naprapater är legitimerade av Socialstyrelsen efter fyra års heltidsutbildning.",
    treats: [
      "Nack- och ryggsmärta",
      "Ischias och utstrålande smärta",
      "Huvudvärk av spänningstyp",
      "Musarm, tennisarmbåge och axelbesvär",
      "Idrotts- och belastningsskador",
    ],
  },
  kiropraktor: {
    title: "Kiropraktik",
    description:
      "Kiropraktik är en legitimerad vårdform inriktad på diagnos och behandling av besvär i rörelseapparaten – särskilt rygg, nacke och leder. Kiropraktorn använder specifika justeringar (manipulation) tillsammans med mjukdelsbehandling och rehabilitering.",
    treats: [
      "Låsningar och stelhet i rygg och nacke",
      "Diskbråck och ischias",
      "Yrsel och huvudvärk från nacken",
      "Käkbesvär (TMD)",
    ],
  },
  massage: {
    title: "Massage",
    description:
      "Klassisk och medicinsk massage används för att minska muskelspänningar, öka cirkulationen och främja återhämtning. Ofta som komplement till naprapatisk eller kiropraktisk behandling.",
    treats: [
      "Stress- och spänningsrelaterade besvär",
      "Träningsvärk och stel muskulatur",
      "Förebyggande underhåll för kontorsarbete",
    ],
  },
};

// Returns 5–6 Q&A entries suitable for on-page FAQ + FAQPage JSON-LD.
// Mixes clinic-specific (address, boka) with evergreen (vad kostar, hur går det till).
export function getClinicFaq(
  clinic: Clinic,
  city: City,
): { q: string; a: string }[] {
  const serviceName =
    serviceLabels[clinic.services[0]].singular.toLowerCase();
  const price = priceLevelInfo[clinic.priceLevel];

  return [
    {
      q: `Var ligger ${clinic.name}?`,
      a: `${clinic.name} finns på ${clinic.street}, ${clinic.postal} i stadsdelen ${clinic.neighborhood}, ${city.name}.`,
    },
    {
      q: `Hur bokar jag tid hos ${clinic.name}?`,
      a: clinic.bookingUrl
        ? `Du kan boka tid online direkt via klinikens bokningssystem${
            clinic.phone ? ` eller ringa ${clinic.phone}` : ""
          }.`
        : clinic.phone
          ? `Ring ${clinic.phone} för att boka tid. Kliniken har inte online-bokning i skrivande stund.`
          : `Kontakta kliniken direkt via deras webbsida för att boka tid.`,
    },
    {
      q: `Vad kostar en behandling hos ${clinic.name}?`,
      a: `${clinic.name} ligger på prisnivå ${price.dots} (${price.label}) – ${price.range} för en standardbehandling. Första besöket är ofta något längre och kan kosta mer. Kontakta kliniken för aktuell prislista.`,
    },
    {
      q: `Vad händer vid mitt första besök?`,
      a: `Vid första besöket gör ${serviceName}en en anamnes (samtal om dina besvär), följt av en fysisk undersökning för att lokalisera orsaken. Därefter påbörjas behandling och du får med dig råd om träning eller ergonomi. Räkna med 45–60 minuter.`,
    },
    {
      q: `Är ${clinic.name} legitimerad vårdgivare?`,
      a: `Ja. ${clinic.name} drivs av legitimerad ${serviceName} registrerad hos Socialstyrelsen. Nakima verifierar alla kliniker innan de publiceras i katalogen.`,
    },
    {
      q: `Kan jag använda friskvårdsbidrag hos ${clinic.name}?`,
      a: `Massage täcks av friskvårdsbidraget hos de flesta arbetsgivare. Naprapati och kiropraktik räknas normalt som sjukvård och täcks inte av friskvårdsbidrag, men kan vara avdragsgillt via privat vårdförsäkring. Kontrollera med kliniken och din arbetsgivare.`,
    },
  ];
}


