/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnsvarsfriskrivningRouteImport } from './routes/ansvarsfriskrivning'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceCityRouteImport } from './routes/$service.$city'
import { Route as MagasinIndexRouteImport } from './routes/magasin.index'
import { Route as MagasinSlugRouteImport } from './routes/magasin.$slug'
import { Route as ServiceCityIndexRouteImport } from './routes/$service.$city.index'
import { Route as ServiceCityClinicRouteImport } from './routes/$service.$city.$clinic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnsvarsfriskrivningRoute = AnsvarsfriskrivningRouteImport.update({
  id: '/ansvarsfriskrivning',
  path: '/ansvarsfriskrivning',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCityRoute = ServiceCityRouteImport.update({
  id: '/$service/$city',
  path: '/$service/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const MagasinIndexRoute = MagasinIndexRouteImport.update({
  id: '/magasin/',
  path: '/magasin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagasinSlugRoute = MagasinSlugRouteImport.update({
  id: '/magasin/$slug',
  path: '/magasin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCityIndexRoute = ServiceCityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceCityRoute,
} as any)
const ServiceCityClinicRoute = ServiceCityClinicRouteImport.update({
  id: '/$clinic',
  path: '/$clinic',
  getParentRoute: () => ServiceCityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ansvarsfriskrivning': typeof AnsvarsfriskrivningRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$service/$city': typeof ServiceCityRouteWithChildren
  '/magasin/$slug': typeof MagasinSlugRoute
  '/magasin/': typeof MagasinIndexRoute
  '/$service/$city/$clinic': typeof ServiceCityClinicRoute
  '/$service/$city/': typeof ServiceCityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ansvarsfriskrivning': typeof AnsvarsfriskrivningRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/magasin/$slug': typeof MagasinSlugRoute
  '/magasin': typeof MagasinIndexRoute
  '/$service/$city/$clinic': typeof ServiceCityClinicRoute
  '/$service/$city': typeof ServiceCityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ansvarsfriskrivning': typeof AnsvarsfriskrivningRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$service/$city': typeof ServiceCityRouteWithChildren
  '/magasin/$slug': typeof MagasinSlugRoute
  '/magasin/': typeof MagasinIndexRoute
  '/$service/$city/$clinic': typeof ServiceCityClinicRoute
  '/$service/$city/': typeof ServiceCityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ansvarsfriskrivning'
    | '/integritetspolicy'
    | '/sitemap.xml'
    | '/$service/$city'
    | '/magasin/$slug'
    | '/magasin/'
    | '/$service/$city/$clinic'
    | '/$service/$city/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ansvarsfriskrivning'
    | '/integritetspolicy'
    | '/sitemap.xml'
    | '/magasin/$slug'
    | '/magasin'
    | '/$service/$city/$clinic'
    | '/$service/$city'
  id:
    | '__root__'
    | '/'
    | '/ansvarsfriskrivning'
    | '/integritetspolicy'
    | '/sitemap.xml'
    | '/$service/$city'
    | '/magasin/$slug'
    | '/magasin/'
    | '/$service/$city/$clinic'
    | '/$service/$city/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnsvarsfriskrivningRoute: typeof AnsvarsfriskrivningRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServiceCityRoute: typeof ServiceCityRouteWithChildren
  MagasinSlugRoute: typeof MagasinSlugRoute
  MagasinIndexRoute: typeof MagasinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ansvarsfriskrivning': {
      id: '/ansvarsfriskrivning'
      path: '/ansvarsfriskrivning'
      fullPath: '/ansvarsfriskrivning'
      preLoaderRoute: typeof AnsvarsfriskrivningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$service/$city': {
      id: '/$service/$city'
      path: '/$service/$city'
      fullPath: '/$service/$city'
      preLoaderRoute: typeof ServiceCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magasin/': {
      id: '/magasin/'
      path: '/magasin'
      fullPath: '/magasin/'
      preLoaderRoute: typeof MagasinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magasin/$slug': {
      id: '/magasin/$slug'
      path: '/magasin/$slug'
      fullPath: '/magasin/$slug'
      preLoaderRoute: typeof MagasinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$service/$city/': {
      id: '/$service/$city/'
      path: '/'
      fullPath: '/$service/$city/'
      preLoaderRoute: typeof ServiceCityIndexRouteImport
      parentRoute: typeof ServiceCityRoute
    }
    '/$service/$city/$clinic': {
      id: '/$service/$city/$clinic'
      path: '/$clinic'
      fullPath: '/$service/$city/$clinic'
      preLoaderRoute: typeof ServiceCityClinicRouteImport
      parentRoute: typeof ServiceCityRoute
    }
  }
}

interface ServiceCityRouteChildren {
  ServiceCityClinicRoute: typeof ServiceCityClinicRoute
  ServiceCityIndexRoute: typeof ServiceCityIndexRoute
}

const ServiceCityRouteChildren: ServiceCityRouteChildren = {
  ServiceCityClinicRoute: ServiceCityClinicRoute,
  ServiceCityIndexRoute: ServiceCityIndexRoute,
}

const ServiceCityRouteWithChildren = ServiceCityRoute._addFileChildren(
  ServiceCityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnsvarsfriskrivningRoute: AnsvarsfriskrivningRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServiceCityRoute: ServiceCityRouteWithChildren,
  MagasinSlugRoute: MagasinSlugRoute,
  MagasinIndexRoute: MagasinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
